### ISSUE TITLE
Druid isn't working with Grafana V8

### ISSUE THREAD

**Issue by RidolfoFabien** [grafadruid/druid-grafana#105]
Hello,

It's seems Druid plugin failed to load with grafana V8 
Do you have the same issue ?
![Druidfailedgrafana](https://user-images.githubusercontent.com/57175447/134031326-2c42f373-7861-4b20-ada4-52c8ae2af5d5.png)
 
Thanks for your help,

Regards,

**Comment by jbguerraz** [comment]
Hello @RidolfoFabien 
We're using it with grafana 8, didn't have any issue so far.
How did you install the plugin (so I can try to reproduce the issue) ?

**Comment by RidolfoFabien** [comment]
Hello @jbguerraz 
I'm sorry I did a mistake indeed I was with grafana 8.1.4 and grafadruid 1.1.0 
I just updated Grafadruid and now it's working very well 
It was a false alarm ...

My bad,

Thanks for your quick answer
