### ISSUE TITLE
Trying to get Druid Plugin to work via datasources.yaml but unsure what the configuration needs to be. It is not documented

### ISSUE THREAD

**Issue by alonbecker** [grafadruid/druid-grafana#106]
Configuration works great via the UI, but when I am trying to set it up via conf/provisioning/datasources it fails with 

**_POST /druid/v2/sql giving up after 1 attempt(s): Post "/druid/v2/sql": unsupported protocol scheme ""_**

**Comment by alonbecker** [comment]
My configuration is something like this:

apiVersion: 1

datasources:
 - name: Druid
   type: grafadruid-druid-datasource 
   access: direct
   orgId: 1
   url: https://urltodruid
   basicAuth: false
   withCredentials: false
   jsonData:
      tlsAuth: false
   editable: true

**Comment by raakasf** [comment]
Hi @alonbecker you can check a sample configuration that is imported by default for plugin testing. The file in dir docker/grafana/provisioning/datasources/druid.yml here's a link to that: https://github.com/IDS/druid-grafana/blob/bbe13e3af1fad19b3fd4f923593bc5a2d868f137/docker/grafana/provisioning/datasources/druid.yml

**Comment by jbguerraz** [comment]
@alonbecker try that link https://github.com/grafadruid/druid-grafana/blob/master/docker/grafana/provisioning/datasources/druid.yml

**Comment by alonbecker** [comment]
Thanks, that is helpful
