### ISSUE TITLE
Granularity fifteen_minute in Druid SQL

### ISSUE THREAD

**Issue by MathieuEtchepare** [grafadruid/druid-grafana#110]
Hello, 

I am currently using this plugin in SQL mode and I wondered if someone knew a way to have the fifteen minute granularity.
For now, I think I can only use rounded units such as MINUTE and HOUR and I would like to have one in between.

`SELECT FLOOR("__time" TO MINUTE) as "time"`

Thank you

**Comment by jbguerraz** [comment]
Hello @MathieuEtchepare 

>TIME_FLOOR(<timestamp_expr>, <period>, [<origin>, [<timezone>]])
Rounds down a timestamp, returning it as a new timestamp. Period can be any ISO8601 period, like P3M (quarters) or PT12H (half-days). The time zone, if provided, should be a time zone name like "America/Los_Angeles" or offset like "-08:00". This function is similar to FLOOR but is more flexible.

(from https://druid.apache.org/docs/latest/querying/sql.html#time-functions)

Is probably what you need. e.g: `SELECT TIME_FLOOR("__time", 'PT15M') as "time"`

**Comment by MathieuEtchepare** [comment]
Hello,

This is exactly what I needed thank you very much 😄
