### ISSUE TITLE
Global variables ${__from}/${__to} on a Druid SQL statement

### ISSUE THREAD

**Issue by layoaster** [grafadruid/druid-grafana#111]
I'm playing with the SQL query editor but I cannot make these expressions work:

```sql
SELECT MILLIS_TO_TIMESTAMP(${__from})
```
I got the SQL parse error:

```
error with code 400 POST http://druid-dremel-lab-routers.default.svc.cluster.local:80/druid/v2/sql message: SQL parse failed
```
Another expression with the same issue:

```sql
SELECT __time AS "timestamp", Source, COUNT(*) AS "num_devices"
FROM "emea-realtime-prod"
WHERE (CustomerId=54) AND TIMESTAMPDIFF(DAY, MILLIS_TO_TIMESTAMP(${__from}), MILLIS_TO_TIMESTAMP(${__to})) <= 4
GROUP BY __time, Source, DeviceId
```

I've tried adding single quotes around the global variables but I got the same error. What am I doing wrong ?

I'm using the latest version of the plugin on Grafana 8.2.3

**Comment by jbguerraz** [comment]
Hello @layoaster 
I've just try to run `SELECT MILLIS_TO_TIMESTAMP(${__from})` and it went fine. 
Are you running it from Explore ? are you sure the interval (`__from`  / `__to`) is actually defined ?
You can use the query inspector to check that; also there you can see the generated query with replacements on `request.data.queries[].builder.query`.

**Comment by layoaster** [comment]
Hi @jbguerraz

For some reason I cannot explain, the behavior reported is no longer happening. It's working just fine. The same day that I opened this issue the same query worked but inside a chart so I immediately thought it was an issue with the query editor.

Sorry to waste your time and thanks for your support!
