### ISSUE TITLE
pie chart v2 works wrong

### ISSUE THREAD

**Issue by wattsun110** [grafadruid/druid-grafana#112]
the sql is: 
select c,__time,diagnosticsInfoAbstract from (select  count(1) as c,max(__time) as __time, diagnosticsInfoAbstract from yarn_app_container_metrics where  __time >= MILLIS_TO_TIMESTAMP(${__from}) and __time <= MILLIS_TO_TIMESTAMP(${__to})  and clusterId='${clusterId}'  and containerExitStatus='${containerExitStatus}' group by  diagnosticsInfoAbstract order by c desc )

when we choose Table, we can see the result returned by druid is just as we expected
![1639638171(1)](https://user-images.githubusercontent.com/80801020/146323715-56ec31cd-bb92-4ba4-9721-eede2089a59a.png)

 but we want to switch to Pie chart v2 , it looks a bit incorrect：
![1639638299(1)](https://user-images.githubusercontent.com/80801020/146323983-45149e14-edb0-4a2d-b2ed-3d0cd3131816.png)

is this a bug?

**Comment by jbguerraz** [comment]
Hello @wattsun110 
If it works well with table, then I assume it's the response format that could be wrong ( https://raw.githubusercontent.com/grafadruid/druid-grafana/master/src/img/screenshot-querybuilder-settings.png ). You could try to set it to `wide`

**Comment by wattsun110** [comment]
hello @jbguerraz , ,thanks for your reply.
yes, I did set the format wide and also do some other settings, then the pie chart v2 :
looks like this:
![1640078837(1)](https://user-images.githubusercontent.com/80801020/146905568-984b397f-f2ca-40b6-8650-13fdcf3f8de1.png)

and what we want is as bellow:
![1640079196(1)](https://user-images.githubusercontent.com/80801020/146906463-fbe89575-b4de-44fb-98fd-af0a0712e23b.png)

and the chart color different from each othe.

yours
watt

**Comment by jbguerraz** [comment]
Hello @wattsun110 
Same label, same color. Here it's all "c". 
We do have some pie charts with different colors, we have a column with the group name then (time, group, value) so I bet you can change your query to do the same thing (probably select "cpu").
The second charts you're showing do some automatic renaming, what's the datasource that does that ? so we can take a look on the logic it uses and see if it makes sens to do the same for grafadruid :)

**Comment by aitanaargu** [comment]
Hi,

I have also a problem with pie chart.

I have a data base with different columns and I want to show them in a pie chart

Filter by some date and then showing sum of column1, sum of column2, sum of column3...

Any help would be appreciated it

Best

**Comment by jbguerraz** [comment]
Hello @aitanaargu 
Sounds like a query issue, not a grafadruid one.

@wattsun110 did you fix the issue ? can we close that issue ?

**Comment by wattsun110** [comment]
> Hello @aitanaargu Sounds like a query issue, not a grafadruid one.
> 
> @wattsun110 did you fix the issue ? can we close that issue ?

yes， please close the issue，thanks

**Comment by jbguerraz** [comment]
roger that
