### ISSUE TITLE
Issue with format Wide 

### ISSUE THREAD

**Issue by Davonex** [grafadruid/druid-grafana#116]
Hello 
I have two cases :
The first it is working well  with l'option wide, I have the aggregation by partition name
![ScreenShot359](https://user-images.githubusercontent.com/17344637/151552553-fa734474-d463-407a-988e-c41726eaf302.jpg)
 
An second case it doesn't working with the same options , i don't have  aggregation by data source 
![ScreenShot360](https://user-images.githubusercontent.com/17344637/151552970-903ed9d2-277c-4782-b5b0-da2c3c06a338.jpg)

Do you have any idea what the problem is?

regards

**Comment by jbguerraz** [comment]
Hello @Davonex 
We're using https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go/data#LongToWide
Maybe ```An error is returned if any of the following are true: The input frame is not a long formatted time series frame. The input frame's Fields are of length 0. The time index is not sorted ascending by time. The time index has null values.``` is a reason ? like not sorted by time ? one of my team mate also reported maybe it expects one entry per time interval per label, a missing group by clause could then be a reason ?
You could try first to sort by time and then to group by time at the needed interval and let us know :)
Thank you!

**Comment by Davonex** [comment]
Hello 
Sorry for my late response 
I tried by sorting the date and  indeed i get an aggregation 

Thank your  for your advise .
