### ISSUE TITLE
Grafana does not support Druid Moving Average Query with error: "unsupported type query"

### ISSUE THREAD

**Issue by NikitaElmanov** [grafadruid/druid-grafana#119]
I use next Grafana version:
<img width="338" alt="Снимок экрана 2022-06-02 в 11 31 26" src="https://user-images.githubusercontent.com/39399744/171589125-871837e0-8bf1-4f98-8e21-a9533f8fc7fa.png">

druid plugin version equals 1.2.0 and with this setup I receive error below:

 <img width="1158" alt="Снимок экрана 2022-06-02 в 10 50 05" src="https://user-images.githubusercontent.com/39399744/171588764-b3bdd245-8156-4c72-ad5f-3779e9f4c1b6.png">

Prompt please, what druid plugin and grafana versions support moving-average query?

**Comment by NikitaElmanov** [comment]
@jbguerraz Hello!

> If you're willing to contribute to the project to bring that new query type I'll be happy to help you doing so!

No, I'm not planing to contribute.
Did I correct understand that you're not going to add this functional in the near future?

**Comment by jbguerraz** [comment]
I, personally, won't until we face the need for it.

**Comment by NikitaElmanov** [comment]
Ok)
