### ISSUE TITLE
Please add version compatibility matrix

### ISSUE THREAD

**Issue by christian-schlichtherle** [grafadruid/druid-grafana#122]
I love this project - I really do! It just took me a while to figure that version 1.3.0 isn't working with Grafana 9.0.5. It works fine with Grafana 8.5.9. Maybe you can add a version compatibility matrix to the README.md?

**Comment by raakasf** [comment]
Thanks @christian-schlichtherle! Great idea, I think it may just be the sdk versions are older and may need to be updated in package.json

```sh
    "@grafana/data": "8.4.3",
    "@grafana/runtime": "8.4.3",
    "@grafana/toolkit": "8.4.3",
    "@grafana/ui": "8.4.3",
```
We may have to compile and test. I can take a look at this later in the week. Or if you like you could try to compile it locally using the docker toolbox and create a PR.

**Comment by bhuvanp1305** [comment]
@ Can we add one more thing Druid version compatibility with this plugin in the compatibility matrix?

**Comment by jbguerraz** [comment]
Great idea!
One would need to keep an eye on new druid and grafana versions and either look at their changelogs or give the plugin a try and then update the readme.
At least we can add a note "Tested until Grafana XXXX and Druid XXX" each time we produce a release and add a static mention "should probably work with newer versions, feel free to report if not".
If one is willing to monitor Grafana and Druid releases and test the plugin to produce a complete matrix that would be awesome ! :fireworks:

**Comment by jbguerraz** [comment]
FYI @christian-schlichtherle Just release 1.4.0 with support for latest Grafana (9.1.6) and latest Druid (24.0.0) https://github.com/grafadruid/druid-grafana/releases/tag/v1.4.0 
Grafana will soon review the new version:
![image](https://user-images.githubusercontent.com/861556/193476796-089edf17-e6c6-4403-89c0-50b94fa62359.png)
