### ISSUE TITLE
Some grafana built-in variables are not expanded

### ISSUE THREAD

**Issue by kwapik** [grafadruid/druid-grafana#124]
Some Grafana built-in variables, including `${__interval_ms}` and `${__interval}` are not expanded properly when used in the plugin.

In other plugins, those are interpolated in the backend, see:
* https://github.com/grafana/grafana/blob/main/pkg/tsdb/loki/parse_query.go#L14
* https://github.com/grafana/grafana/blob/main/pkg/tsdb/prometheus/models/query.go#L15

The goal of this issue is:
1. To figure out why those variables are treated differently,
2. Implement similar behavior in this plugin.

**Comment by jbguerraz** [comment]
@kwapik FYI https://github.com/grafadruid/druid-grafana/pull/126 - gonna release 1.4.0 now with support for latest grafana and druid versions

**Comment by kwapik** [comment]
Started working on this.
