### ISSUE TITLE
Getting rpc error when making post aggregation type  `quantilesDoublesSketchToHistogram`

### ISSUE THREAD

**Issue by saketbairoliya2** [grafadruid/druid-grafana#132]
Here is my query: 

```
{
  "queryType": "timeseries",
  "dataSource": "dc_94b4f5fdfde940979b79c50539d8322a_b42fde98efed4e638a0016b34b3c10cf_dataset_label",
  "granularity": "all",
  "aggregations": [
    {
      "type": "quantilesDoublesSketch",
      "fieldName": "double_sketch",
      "k": 1024,
      "name": "quantile_sketch"
    }
  ],
  "postAggregations": [
    {
      "type": "quantilesDoublesSketchToHistogram",
      "name": "histogram",
      "numBins": 50,
      "field": {
        "fieldName": "quantile_sketch",
        "name": "quantile_sketch",
        "type": "fieldAccess"
      }
    }
  ],
  "intervals": "2022-08-28/2022-10-20"
}
```

I get an rpc error. The same query works when executed via druid or via SQL command. Can you please help here? @jbguerraz

**Comment by saketbairoliya2** [comment]
Any updated on this @jbguerraz ?

**Comment by saketbairoliya2** [comment]
We're able to connect to druid and get back the response but looks like the response.Frame object errors because of list of numbers are being returned instead of individual value. Any suggestion to fix this?

**Comment by jbguerraz** [comment]
Hello @saketbairoliya2 
See https://github.com/grafadruid/druid-grafana/issues/94
Probably we can close this one (I let you do so if you think so as well)

**Comment by saketbairoliya2** [comment]
Not required anymore. Closing this.
