### ISSUE TITLE
Possible bug when using expressions and ${__from} or ${__to} variables

### ISSUE THREAD

**Issue by alvaro-ponce** [grafadruid/druid-grafana#137]
hi!
I am using the last version of the plugin (1.4) in my Grafana version v8.3.2

I have just found that if I am creating a Panel with some SQL queries filtering the time field with __from and __to variables like  `__time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})` I can not add a Math Expression because if so, the query fails.

As you can see in next logs, when no using a Math Expression the __from and __to are correctly parsed:
* Log with query:
`
t=2023-01-09T18:25:35+0000 lvl=info msg="DRUID EXECUTE QUERY" logger=plugin.initializer pluginID=grafadruid-druid-datasource _________________________DRUID QUERY___________________________="map[query:SELECT\r\n    floor (\"__time\" to hour) as \"time\" \r\n    ,avg(\"value\") \r\nFROM\r\n    \"some-table\"\r\nWHERE\r\n     \"tag\" IN ('some_tag') \r\n     and __time >= MILLIS_TO_TIMESTAMP(1673245534983) AND __time <= MILLIS_TO_TIMESTAMP(1673288734983) \r\n\r\nGROUP BY \r\n    FLOOR (\"__time\" to hour) queryType:sql]"
`

But the exact same query fails when adding a Math Expression because of the $ character in the __from and __to variables as it seems that they are not being parsed as you can see in the log of the query:
* Log with query:
`
t=2023-01-09T18:17:43+0000 lvl=info msg="DRUID EXECUTE QUERY" logger=plugin.initializer pluginID=grafadruid-druid-datasource _________________________DRUID QUERY___________________________="map[query:SELECT\r\n    floor (\"__time\" to hour) as \"time\"\r\n    ,avg(\"value\") \r\n FROM\r\n  \"some-table\"\r\nWHERE\r\n     \"tag\" IN ('some_tag') \r\n     and __time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to}) \r\n\r\nGROUP BY \r\n    FLOOR (\"__time\" to hour)  queryType:sql]"
`
* Error:
`
t=2023-01-09T18:17:43+0000 lvl=eror msg="expression request error" logger=context userId=1 orgId=1 uname=admin error="failed to execute query J10: POST http://xxxx/druid/v2/sql giving up after 1 attempt(s): failed to query Druid: {Error:SQL parse failed ErrorMessage:Encountered \"( $\" at line 8, column 39.\nWas expecting one of:\n    \".\" ...\n    \"(\" ...\n    \"(\" \"*\" ...\n    \"(\" \")\" ...\n    \"(\" \"DISTINCT\" ...\n    \"(\" \"ALL\" ...\n    \"(\" <IDENTIFIER> ...\n    \"(\" <QUOTED_IDENTIFIER> ...\n    \"(\" <BACK_QUOTED_IDENTIFIER> ...\n    \"(\" <BRACKET_QUOTED_IDENTIFIER> ...\n    \"(\" <UNICODE_QUOTED_IDENTIFIER> ...\n    \"(\" \"DEFAULT\" ...\n    \"(\" \"WITH\" ...\n    \"(\" \"+\" ...\n    \"(\" \"-\" ...\n    \"(\" \"NOT\" ...\n    \"(\" \"EXISTS\" ...\n    \"(\" <UNSIGNED_INTEGER_LITERAL> ...\n    \"(\" <DECIMAL_NUMERIC_LITERAL> ...\n    \"(\" <APPROX_NUMERIC_LITERAL> ...\n    \"(\" <BINARY_STRING_LITERAL> ...\n    \"(\" <PREFIXED_STRING_LITERAL> ...\n    \"(\" <QUOTED_STRING> ...\n    \"(\" <UNICODE_STRING_LITERAL> ...\n    \"(\" \"TRUE\" ...\n    \"(\" \"FALSE\" ...\n    \"(\" \"UNKNOWN\" ...\n    \"(\" \"NULL\" ...\n    \"(\" <LBRACE_D> ...\n    \"(\" <LBRACE_T> ...\n    \"(\" <LBRACE_TS> ...\n    \"(\" \"DATE\" ...\n    \"(\" \"TIME\" ...\n    \"(\" \"TIMESTAMP\" ...\n    \"(\" \"INTERVAL\" ...\n    \"(\" \"?\" ...\n    \"(\" \"CAST\" ...\n    \"(\" \"EXTRACT\" ...\n    \"(\" \"POSITION\" ...\n    \"(\" \"CONVERT\" ...\n    \"(\" \"TRANSLATE\" ...\n    \"(\" \"OVERLAY\" ...\n    \"(\" \"FLOOR\" ...\n    \"(\" \"CEIL\" ...\n    \"(\" \"CEILING\" ...\n    \"(\" \"SUBSTRING\" ...\n    \"(\" \"TRIM\" ...\n    \"(\" \"CLASSIFIER\" ...\n    \"(\" \"MATCH_NUMBER\" ...\n    \"(\" \"RUNNING\" ...\n    \"(\" \"PREV\" ...\n    \"(\" \"NEXT\" ...\n    \"(\" \"JSON_EXISTS\" ...\n    \"(\" \"JSON_VALUE\" ...\n    \"(\" \"JSON_QUERY\" ...\n    \"(\" \"JSON_OBJECT\" ...\n    \"(\" \"JSON_OBJECTAGG\" ...\n    \"(\" \"JSON_ARRAY\" ...\n    \"(\" \"JSON_ARRAYAGG\" ...\n    \"(\" <LBRACE_FN> ...\n    \"(\" \"MULTISET\" ...\n    \"(\" \"ARRAY\" ...\n    \"(\" \"PERIOD\" ...\n    \"(\" \"SPECIFIC\" ...\n    \"(\" \"ABS\" ...\n    \"(\" \"AVG\" ...\n    \"(\" \"CARDINALITY\" ...\n    \"(\" \"CHAR_LENGTH\" ...\n    \"(\" \"CHARACTER_LENGTH\" ...\n    \"(\" \"COALESCE\" ...\n    \"(\" \"COLLECT\" ...\n    \"(\" \"COVAR_POP\" ...\n    \"(\" \"COVAR_SAMP\" ...\n    \"(\" \"CUME_DIST\" ...\n    \"(\" \"COUNT\" ...\n    \"(\" \"CURRENT_DATE\" ...\n    \"(\" \"CURRENT_TIME\" ...\n    \"(\" \"CURRENT_TIMESTAMP\" ...\n    \"(\" \"DENSE_RANK\" ...\n    \"(\" \"ELEMENT\" ...\n    \"(\" \"EXP\" ...\n    \"(\" \"FIRST_VALUE\" ...\n    \"(\" \"FUSION\" ...\n    \"(\" \"GROUPING\" ...\n    \"(\" \"HOUR\" ...\n    \"(\" \"LAG\" ...\n    \"(\" \"LEAD\" ...\n    \"(\" \"LEFT\" ...\n    \"(\" \"LAST_VALUE\" ...\n    \"(\" \"LN\" ...\n    \"(\" \"LOCALTIME\" ...\n    \"(\" \"LOCALTIMESTAMP\" ...\n    \"(\" \"LOWER\" ...\n    \"(\" \"MAX\" ...\n    \"(\" \"MIN\" ...\n    \"(\" \"MINUTE\" ...\n    \"(\" \"MOD\" ...\n    \"(\" \"MONTH\" ...\n    \"(\" \"NTH_VALUE\" ...\n    \"(\" \"NTILE\" ...\n    \"(\" \"NULLIF\" ...\n    \"(\" \"OCTET_LENGTH\" ...\n    \"(\" \"PERCENT_RANK\" ...\n    \"(\" \"POWER\" ...\n    \"(\" \"RANK\" ...\n    \"(\" \"REGR_COUNT\" ...\n    \"(\" \"REGR_SXX\" ...\n    \"(\" \"REGR_SYY\" ...\n    \"(\" \"RIGHT\" ...\n    \"(\" \"ROW_NUMBER\" ...\n    \"(\" \"SECOND\" ...\n    \"(\" \"SQRT\" ...\n    \"(\" \"STDDEV_POP\" ...\n    \"(\" \"STDDEV_SAMP\" ...\n    \"(\" \"SUM\" ...\n    \"(\" \"UPPER\" ...\n    \"(\" \"TRUNCATE\" ...\n    \"(\" \"USER\" ...\n    \"(\" \"VAR_POP\" ...\n    \"(\" \"VAR_SAMP\" ...\n    \"(\" \"YEAR\" ...\n    \"(\" \"CURRENT_CATALOG\" ...\n    \"(\" \"CURRENT_DEFAULT_TRANSFORM_GROUP\" ...\n    \"(\" \"CURRENT_PATH\" ...\n    \"(\" \"CURRENT_ROLE\" ...\n    \"(\" \"CURRENT_SCHEMA\" ...\n    \"(\" \"CURRENT_USER\" ...\n    \"(\" \"SESSION_USER\" ...\n    \"(\" \"SYSTEM_USER\" ...\n    \"(\" \"NEW\" ...\n    \"(\" \"CASE\" ...\n    \"(\" \"CURRENT\" ...\n    \"(\" \"CURSOR\" ...\n    \"(\" \"ROW\" ...\n    \"(\" \"(\" ...\n    \"(\" \"SELECT\" ...\n    \"(\" \"VALUES\" ...\n    \"(\" \"TABLE\" ...\n     ErrorClass:org.apache.calcite.sql.parser.SqlParseException Host:}" remote_addr="xxxx, xxx"
`

It would be nice if you could give me some hints, I do not know if this is a known issue or if there are other ways to use math expressions. 

Thank you in advance

**Comment by StanDye** [comment]
? Looks like your second query is missing the FROM

**Comment by alvaro-ponce** [comment]
Nope, my bad I edited the name of the table and the name of the tag filtered and probably deleted the "From" part of the query.

I edited the first comment with the correct query, the bug is still happening.
