### ISSUE TITLE
Stop Auto Query submit

### ISSUE THREAD

**Issue by MohammadGhazanfar** [grafadruid/druid-grafana#141]
The auto query submit becomes a real pain when using Grafana's "Explore" or even when writing complex queries while creating panels. Constantly throws up errors - is very ugly when creating alerts as well.

The [BigQuery Plugin](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) solves this by having a "Run query" button. See the screen shot below,

<img width="1257" alt="Screenshot 2023-01-27 at 12 26 52 PM" src="https://user-images.githubusercontent.com/14135427/215027464-c1a1bcbf-7e1a-4c7d-9bc2-55e80f21ce64.png">

Can we introduce something like this here as well please?

@jbguerraz I'll be happy to make the change and submit a PR if you can help me out a little with where the changes for this might go in.

**Comment by jbguerraz** [comment]
Hello @MohammadGhazanfar 
You can already configure the debouncing either at datasource level ( https://github.com/grafadruid/druid-grafana#datasource---default-settings ) and/or at query level ( https://github.com/grafadruid/druid-grafana#query-builder---settings ). A high value will basically "disable" it (like if you enter one hour).

I'm fine with a run query button contribution (despite we can already click the reload icon to fire a query).

**Comment by MohammadGhazanfar** [comment]
@jbguerraz are you okay with totally removing the "debouncing feature"? I don't think it is useful. No one in my team likes it either.

**Comment by MohammadGhazanfar** [comment]
Also, @jbguerraz, setting the debouncing at the datasource level doesn't seem to be working 🐛

**Comment by jbguerraz** [comment]
Hello @MohammadGhazanfar 
I don't think removing the debouncing is a great thing, some ppl may actually be using it (it'll kill the backward compatibility).
We may change the default value to something higher may be but really you can deploy it with a big value and it'll looks like it's disabled for you if you don't like it.
Do you have a value set at query level ? it uses the datasource level one when there is no override at query level. The only known "issue" (actually, feature request) around the query settings is that one https://github.com/grafadruid/druid-grafana/issues/87

**Comment by MohammadGhazanfar** [comment]
> I don't think removing the debouncing is a great thing, some ppl may actually be using it (it'll kill the backward compatibility).

Sounds good!

>We may change the default value to something higher may be but really you can deploy it with a big value and it'll looks like it's disabled for you if you don't like it.

Yeah, I am planning on doing that - but the value specified at the datasource level seems to be ignored. Value specified at the query level still works.

>Do you have a value set at query level ? it uses the datasource level one when there is no override at query level. The only known "issue" (actually, feature request) around the query settings is that one https://github.com/grafadruid/druid-grafana/issues/87

I only specified a value of `10000` at the datasource level - tried it both from the UI and file provisioning. Neither worked. The value shows up in the datasource settings. I had nothing set at the query level. If you don't have the time or aren't able to repro this, I can get back to you with a short video showing what's happening.

**Comment by jbguerraz** [comment]
@MohammadGhazanfar a fix is on its way :) see #149 
if you will to contribute by reviewing the code (and why not by working on the proper merging - see TODO in code) then you're more than welcome!

**Comment by Ghazanfar-CFLT** [comment]
Thank you @jbguerraz!
I will surely have a look at it, but I know very little TypeScript. Really needed this. It's been very annoying.

**Comment by dhia-gharsallaoui** [comment]
Hello @jbguerraz :wave: 
I will work on it if it's still available.
