### ISSUE TITLE
facing issue on grafana 7.3 while adding data source

### ISSUE THREAD

**Issue by Gauravshah** [grafadruid/druid-grafana#25]
while adding the plugin getting following exception:
```
Unexpected token '<' Evaluating https://quanta.goshd.com/public/plugins/grafadruid-druid-datasource/module.js Loading plugins/grafadruid-druid-datasource/module
```
<img width="1485" alt="Screenshot 2021-01-19 at 12 49 03 PM" src="https://user-images.githubusercontent.com/620559/105000757-978d4c00-59e3-11eb-8eb3-4e7ef0016cbb.png">

**Comment by Gauravshah** [comment]
I think the `dist` folder is missing. @jbguerraz please build for all platforms while you are at it :) 

@ShilpaSivanesan do you have commands handy for cross system build ? I remember we doing it for druid backend

**Comment by ShilpaSivanesan** [comment]
Commands to build for platform-specific
```
env GOOS=darwin GOARCH=amd64 go build -o ./dist/druid-plugin_darwin_amd64 .

env GOOS=linux GOARCH=amd64 go build -o ./dist/druid-plugin_linux_amd64 .

env GOOS=windows GOARCH=amd64 go build -o ./dist/druid-plugin_windows_amd64 .

```

**Comment by jbguerraz** [comment]
@Gauravshah  @ShilpaSivanesan  feel free to check `./mage -l`
`./mage` will build backend and frontend by default (so `dist` will appear).
Backend build is multi-platform. But if you  wish you can build the backend for a single platform like `./mage backend:windows`

**Comment by jbguerraz** [comment]
Published a build here https://github.com/grafadruid/druid-grafana/releases/tag/v0.0.2

**Comment by Gauravshah** [comment]
can now install via `grafana-cli --pluginUrl https://github.com/grafadruid/druid-grafana/releases/download/v1.0.0/grafadruid-druid-datasource-1.0.0.zip plugins install grafadruid-druid-datasource`
thanks @jbguerraz
