### ISSUE TITLE
sign backend to remove `unsigned` warning

### ISSUE THREAD

**Issue by Gauravshah** [grafadruid/druid-grafana#27]
https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/

**Comment by jbguerraz** [comment]
@Gauravshah  Yes, this is a WIP; already started the process with Grafana.com mates. Need to publish a build now. Will do so later today.

**Comment by Gauravshah** [comment]
this is like a good to have feature :) would not bother too much about it as of now

**Comment by jbguerraz** [comment]
Thank you @Gauravshah :)
Here it is! I gonna close #26 as it somehow duplicates that one (signing & publishing is the same workflow)

**Comment by jbguerraz** [comment]
(still in progress)

**Comment by gsaiz** [comment]
@jbguerraz Is this still in progress? The plugin can't be used on a managed Grafana instance on grafana.com without being on the official marketplace.

**Comment by jbguerraz** [comment]
Hello @gsaiz 
It's actually ready to go on Grafana side, I had in mind to do it with the next release (hopefully with autocomplete added).
If that's critical for you I can probably release earlier, without autocomplete support.
Let me know!

**Comment by gsaiz** [comment]
Hi @jbonofre,

It's the only thing that's stopping us from using the Grafana SaaS (grafana.com), so it'd be awesome if you could release it early!

Thanks in any case! :)

**Comment by jbguerraz** [comment]
Hi @gsaiz ,

It's (mostly) done! 
https://github.com/grafadruid/druid-grafana/releases/tag/v1.2.0
https://github.com/grafana/grafana-plugin-repository/pull/831#issuecomment-876495504

Now waiting for the merge :)

**Comment by jbguerraz** [comment]
:tada: https://grafana.com/grafana/plugins/grafadruid-druid-datasource/ here it is :)
