### ISSUE TITLE
Intervals not respecting dashboard interval

### ISSUE THREAD

**Issue by Gauravshah** [grafadruid/druid-grafana#29]
I did not understand the use case of having interval option as part of the UI.
<img width="406" alt="Screenshot 2021-01-21 at 5 03 34 PM" src="https://user-images.githubusercontent.com/620559/105345832-9867de80-5b99-11eb-988b-640fe21056ed.png">

I always thought that interval should come from grafana and we should use that

**Comment by jbguerraz** [comment]
You can see an example here: https://github.com/grafadruid/druid-grafana/blob/master/dashboard.json#L171

You have to use `${__from:date:iso}` as interval start and `${__to:date:iso}` as interval stop.

Basically the component will detect the `$` and will then use the variable and print the variable as the input field placeholder.

**Comment by Gauravshah** [comment]
All the plugins on grafana respect that time range filter. It would be odd to expect users to put this in. 

I think what we can do is if no interval is selected then default it to grafana. If interval are user entered then use that. 

So this way normal requests are handled without user having to understand intervals.

**Comment by jbguerraz** [comment]
Here it is @Gauravshah : https://github.com/grafadruid/druid-grafana/pull/31
Feel free to review it :) 
Basically it defaults to the Grafana interval if empty.

**Comment by Gauravshah** [comment]
thanks @jbguerraz
