### ISSUE TITLE
Graph / dashboard examples

### ISSUE THREAD

**Issue by fstolba** [grafadruid/druid-grafana#35]
Trying to play around with this as we've been longing for Druid support in Grafana for what feels like ages. Thanks for building this great plugin and putting it out there. 

While I was able to put together some basic metrics displays (e.g. simple queries for singular metrics) I was struggling with and failed to build some more complex graphs e.g. referencing global variables and such. I assume they would be supported after studying the readme. 

Of course having a proper tutorial would make sense in the long run. For the moment even seeing some screenshots of possible graph configurations/query types/advanced usage examples like variables and formulas along with the results would help kickstart everyone and provide a starting point from which to build upon. I assume the people using your plugin at the moment are probably advanced Grafana users to say the least so this can go a long way.

**Comment by jbguerraz** [comment]
Hello @fstolba 
Thank you for your feedback!
Indeed documentation is still poor, and contribution welcomed :)
We have a sample dashboard here https://github.com/grafadruid/druid-grafana/blob/master/dashboard.json that does work with the Druid wikipedia example. This uses variables (as you can see here https://github.com/grafadruid/druid-grafana/blob/master/dashboard.json#L61 ).
If you feel it, we would be glad to have such kind of contribution and I'll be personally happy to help you moving ahead that contribution path.
Feel free to ping us on Slack!

**Comment by fstolba** [comment]
Hi @jbguerraz thanks for the pointer, having been away from Grafana for some time I missed the demo dashboard in the repo. For the moment I provided a small PR for the README so others will more easily find it.

**Comment by jbguerraz** [comment]
Thank you @fstolba  !!
