### ISSUE TITLE
Query inspector displays binary data instead of JSON

### ISSUE THREAD

**Issue by raakasf** [grafadruid/druid-grafana#41]
The query inspector doesn't display response from Druid as JSON instead just a binary blob:

![Screen Shot 2021-02-25 at 12 08 34 PM](https://user-images.githubusercontent.com/4614260/109345849-c696a900-783e-11eb-994b-4eeb5fa04aa8.png)

It is really helpful for users to be able to see JSON response in order to figure out what/if anything is wrong with their queries.

**Comment by jbguerraz** [comment]
At Grafana level it's not a Druid response, it's DataFrames (Apache Arrow based).
At best we can log the Druid response, actually, we're already doing it there https://github.com/grafadruid/druid-grafana/blob/master/pkg/druid.go#L276
I must confess that golang code isn't (yet) nice and surely when it'll be the moment to refactor it we should keep in mind logging. However at the moment you can watch Grafana logs to get the Druid raw response.
Closing it as I don't see how to move ahead with it. Feel free to re-open if you have something in mind.
