### ISSUE TITLE
Top N query: postAggregations has a bug

### ISSUE THREAD

**Issue by zhangfangkai** [grafadruid/druid-grafana#67]
when i use postAggregations, I select the type is "arithmetic", but the post data is  "cardinality"
<img width="868" alt="2" src="https://user-images.githubusercontent.com/16400894/114165459-177ddf00-995f-11eb-9a89-a35af9352ec4.png">
![111](https://user-images.githubusercontent.com/16400894/114165474-1b116600-995f-11eb-820b-cfa8f77929b3.png)
![111](https://user-images.githubusercontent.com/16400894/114165475-1b116600-995f-11eb-8440-abd5aa6afc8c.png)

**Comment by jbguerraz** [comment]
Hello @zhangfangkai
Thank you for the report! Indeed there is a typo there https://github.com/grafadruid/druid-grafana/blob/master/src/builder/postaggregation/Arithmetic.tsx#L64
I'll provide a fix ASAP

**Comment by jbguerraz** [comment]
@zhangfangkai  here it is, freshly baked https://github.com/grafadruid/druid-grafana/releases/tag/v1.0.3
Feel free to close the issue if it's all right for you :)

**Comment by jbguerraz** [comment]
@zhangfangkai had you any chance to give that release a try? all is fine ?

**Comment by zhangfangkai** [comment]
i haven't try the new release, but thanks for your modify, i think it will be ok!
