### ISSUE TITLE
Some error happen in use this plugin

### ISSUE THREAD

**Issue by ccyaml** [grafadruid/druid-grafana#68]
grafana version: V7.0.3
plugin version: V1.0.3(V1.0.2、V1.0.1、V1.0.0)
when i unzip this plugin in data/plugin , and restart grafana
the log show ```msg="Failed to load plugin" logger=plugins error="plugin \"grafadruid-druid-datasource\" is unsigned"```
show i add ```allow_loading_unsigned_plugins=grafadruid-druid-datasource``` in configure
but when i use this plugin ,there are some error happen
![image](https://user-images.githubusercontent.com/78244312/115334817-a21bd500-a1ce-11eb-9496-17ac3e22858a.png)
maybe it's a frontEnd Error
please help me or give me some advise

**Comment by jbguerraz** [comment]
Hello @ccyaml 
Thank you for the issue!
I've never seen such issue. I don't know what the reason could be.
When do you see this issue ? when adding a data source (see screenshot) ? or you don't even see the plugin listed there ?
![image](https://user-images.githubusercontent.com/861556/115413058-65f36f00-a1e4-11eb-9e09-f12260188784.png)

**Comment by ccyaml** [comment]
Hello @jbguerraz 
when i add data source, i can see the Druid
![image](https://user-images.githubusercontent.com/78244312/115488217-b920fc80-a28c-11eb-9db1-e15dc9161af8.png)
when i click the select button, this error happen
i can see the Druid in my data sources list， but i can't click it and see detail
![image](https://user-images.githubusercontent.com/78244312/115488506-33ea1780-a28d-11eb-89d0-d3d485f98045.png)
i think you can try, use grafana v7.0.3 and Druid pluginV1.0.3
Thanks

**Comment by jbguerraz** [comment]
Hello @ccyaml 
I built the plugin tons of time recently and couldn't reproduce.
Anyway, the master is now providing a refactored version of the plugin, feel free to give it a try and reopen an issue if the issue persists.
Thank you!
