### ISSUE TITLE
Documentation page - contains broken link to demo dashboard.

### ISSUE THREAD

**Issue by DanoOM** [grafadruid/druid-grafana#72]
The demo dashboard link appears to brooken.

https://github.com/grafadruid/druid-grafana/blob/master/dashboard.json

**Comment by jbguerraz** [comment]
Thank you for the issue @DanoOM 
Indeed you're right. Now the dashboard is automatically created when the (docker based) environment starts and the wikipedia sample is automatically ingested so you're all set from start (`mage env:start`).
Would you mind creating a PR to fix the readme ?
Thank you a lot!

**Comment by jbguerraz** [comment]
Fixed :)
