### ISSUE TITLE
how to use IN clause with variable ?

### ISSUE THREAD

**Issue by philippesg** [grafadruid/druid-grafana#93]
Hello, a new question;) How to use multiple values ​​in a variable ?  for example, i dont know how to use  IN clause with variable , this querie doesnt return datas : 

![image](https://user-images.githubusercontent.com/49228865/121550596-293b3b80-ca0f-11eb-8f1b-d9f40ab3531e.png)

**Comment by philippesg** [comment]
Hello, we are very interested in this feature because we will be able to use your plugin with all our graphs. We have tried to use ${hostM:druid:json} and ${hostM:lucene} because we use an ElasticSearch datasource to build the variable hostM in Grafana.

**Comment by jbguerraz** [comment]
Hello @philippesg ,

We do use filters like `AND contract in (${contract:sqlstring})` and it's working fine, I'd be curious to see the generated query. Feel free to join on https://join.slack.com/t/grafadruid/shared_invite/zt-ryrcolyp-GQCiKcOF0WhnK~iqpkrqLA so I can try to help you in a more interactive way :)

**Comment by jbguerraz** [comment]
FYI, I just tested that in latest version to be 100% sure:

![image](https://user-images.githubusercontent.com/861556/122360326-d8af6b00-cf45-11eb-968e-ae59b18086ec.png)

**Comment by philippesg** [comment]
Hello @jbguerraz, thank you for your help. it's worked. I just see that it's my data is in upper case and i must applied lower() function.
